### PR TITLE
changes to resolve config element problem

### LINKED ISSUE #335: Incorrect config element diagnostic with versionless feature
This `mpMetrics` config element should not have a diagnostic since the versionless `mpMetrics` feature is specified.

Screenshot 2025-01-13 at 10 31 28 AM

### PR DESCRIPTION
**Pull request by arunvenmany-ibm**
Fixes #335

### CODE REVIEW

File: lemminx-liberty/src/test/java/io/openliberty/LibertyDiagnosticTest.java [hunk 1]
```diff
@@ -1062,4 +1062,74 @@ public void testMultipleVariablesInSameAttributeDiagnostic() {
...
+        List<String> featuresToAdd = new ArrayList<String>();
+        featuresToAdd.add("mpMetrics-1.0");
+        featuresToAdd.add("mpMetrics-1.1");
+        featuresToAdd.add("mpMetrics-2.0");
+        featuresToAdd.add("mpMetrics-2.2");
+        featuresToAdd.add("mpMetrics-2.3");
+        featuresToAdd.add("mpMetrics-3.0");
+        featuresToAdd.add("mpMetrics-4.0");
+        featuresToAdd.add("mpMetrics-5.0");
+        featuresToAdd.add("mpMetrics-5.1");
```
Comment (cherylking) [inline lemminx-liberty/src/test/java/io/openliberty/LibertyDiagnosticTest.java:1111]: So this is interesting....we are suggesting they add a versioned feature...but they have a platform specified already. Which means it would be better to add the versionless feature. We probably should open an enhancement issue to look into making our quick fix smarter for this scenario.

File: lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/data/FeatureListGraph.java [hunk 2]
```diff
@@ -65,7 +70,7 @@ public ConfigElementNode addConfigElement(String nodeName) {
         }
         ConfigElementNode node = new ConfigElementNode(nodeName);
         configElementNodes.put(nodeName, node);
-        nodes.putIfAbsent(nodeName, node);
+        nodes.put(nodeName, node);
```
[the remark this answers is not in the document]
Comment (arunvenmany-ibm) [reply lemminx-liberty/src/main/java/io/openliberty/tools/langserver/lemminx/data/FeatureListGraph.java:73]: Q1 :- Yes correct
Q2:- Yes I think its okay to go ahead with this, as we are not expecting versionless to have separate enable By options
Q3:- We can modify the logic to ignore versionless feature. But again, this issue is only for mpMetrics , that is the only case where configElementName and featureName are same

File: lemminx-liberty/src/test/java/io/openliberty/LibertyDiagnosticTest.java (hunk 1 above)
Comment (arunvenmany-ibm) [reply lemminx-liberty/src/test/java/io/openliberty/LibertyDiagnosticTest.java:1111]: Done
https://github.com/OpenLiberty/liberty-language-server/issues/342

**Review by cherylking — APPROVED** [review]
